name: self-hosted-runner

on:
  push:
    branches: [ master ]
  
jobs:
  my_job:
    name: zBot
    runs-on: self-hosted
    strategy:     
       matrix:
         node-version: [12.x]
    steps:
      - shell: bash
        run: |
            cd /home/zackkomo/zBot/zBot/zBot/zBot/commands
            cp pollList.json /home/zackkomo
            cp reminderList.json /home/zackkomo
      - uses: actions/checkout@v2
      - name: Run
        run: |
          cd /home/zackkomo/
          cp .env /home/zackkomo/zBot/zBot/zBot/zBot/
          cp pollList.json /home/zackkomo/zBot/zBot/zBot/zBot/commands
          cp reminderList.json /home/zackkomo/zBot/zBot/zBot/zBot/commands
          whoami
          sudo systemctl restart zBot
          sudo systemctl status zBot
         
    
    


