name: self-hosted-runner

on:
  push:
    branches: [ master ]
  
jobs:
  my_job:
    name: zBot
    runs-on: self-hosted
    strategy:     
       matrix:
         node-version: [12.x]
    steps:
      - name: Stopbot
        run: |
              sudo systemctl stop zBot
              
      - name: Preservefiles
        run: |
              cd /home/zackkomo/zBot/zBot/zBot/zBot/commands
              cp pollList.json /home/zackkomo
              cp reminderList.json /home/zackkomo
              
      - name: push
        uses: actions/checkout@master
        
      - name: Restorefiles
        run: |
          cd /home/zackkomo/
          cp .env /home/zackkomo/zBot/zBot/zBot/zBot/
          cp pollList.json /home/zackkomo/zBot/zBot/zBot/zBot/commands
          cp reminderList.json /home/zackkomo/zBot/zBot/zBot/zBot/commands
          
      - name: startbot
        run: |
            sudo systemctl restart zBot
         
    
    


