name: self-hosted-runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: |
        cd /home/zackkomo/
        cp .env /home/zackkomo/zBot/zBot/zBot/zBot/
        cd /home/zackkomo/zBot/zBot/zBot/zBot/
        npm start
        


